openapi: 3.0.0
info:
  version: '1.0.0'
  title: Watcher Info API
  description: >
    API specification of the Watcher's Informational Service

    Error codes are available in [html](https://github.com/omisego/elixir-omg/blob/master/docs/api_specs/errors.md#error-codes-description) format.
  contact:
    name: OmiseGO
    email: omisego@omisego.co
  license:
    name: 'Apache 2.0: https://www.apache.org/licenses/LICENSE-2.0'
    url: 'https://omisego.network/'

servers:
  - url: http://localhost:7534/
  - url: http://localhost:7434/

tags:
  - name: Account
    description: Account related API.
  - name: Block
    description: Block related API.
  - name: Transaction
    description: Transaction related API.
  - name: Fees
    description: Fees related API.

paths:
  /alarm.get:
    $ref: 'alarm/paths.yaml#/alarm.get'
  /account.get_balance:
    $ref: 'account/paths.yaml#/account.get_balance'
  /account.get_utxos:
    $ref: 'account/paths.yaml#/account.get_utxos'
  /account.get_transactions:
    $ref: 'account/paths.yaml#/account.get_transactions'
  /block.get:
    $ref: 'block/paths.yaml#/block.get'
  /block.all:
    $ref: 'block/paths.yaml#/block.all'
  /transaction.all:
    $ref: 'transaction/paths.yaml#/transaction.all'
  /transaction.create:
    $ref: 'transaction/paths.yaml#/transaction.create'
  /transaction.get:
    $ref: 'transaction/paths.yaml#/transaction.get'
  /transaction.submit_typed:
    $ref: 'transaction/paths.yaml#/transaction.submit_typed'
  /fees.all:
    $ref: 'fees/paths.yaml#/fees.all'
