version: "2.1"
services:
  postgres:
    image: postgres:9.6.13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    healthcheck:
      test: pg_isready -U omisego_dev
      interval: 5s
      timeout: 3s
      retries: 5

  watcher:
    #last stable staging and production watcher with ALD, pre-lumphini
    image: omisego/watcher:70e9a68
    command: "full_local"
    environment:
      - ETHEREUM_RPC_URL=https://rinkeby.infura.io/v3/${INFURA_API_KEY}
      - ETHEREUM_WS_RPC_URL=wss://rinkeby.infura.io/ws/v3/${INFURA_API_KEY}
      - CHILD_CHAIN_URL=https://childchain-pre-lumphini.omg.network/
      - ETHEREUM_NETWORK=RINKEBY
      - RINKEBY_TXHASH_CONTRACT=0xefc216dcfb01223253172514355fbe65e60acc043f214a9cdfad1e6f5cb566b4
      - RINKEBY_AUTHORITY_ADDRESS=0x3272b97b7f1b74b338cb0fdda167cf76bc4da3b6
      - RINKEBY_CONTRACT_ADDRESS_PLASMA_FRAMEWORK=0x24e0b6b701c941824b3eedc041f50be6e15bfdeb
      - RINKEBY_CONTRACT_ADDRESS_ETH_VAULT=0x9631a230eaf33b51012fca494e4030d852bb9386
      - RINKEBY_CONTRACT_ADDRESS_ERC20_VAULT=0x88d38a42946c62d32f159880fe2735c0149cca3f
      - RINKEBY_CONTRACT_ADDRESS_PAYMENT_EXIT_GAME=0x51db5309cc89165b5306417b63368acce690355b
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@postgres:5432/omisego_dev
      - NODE_HOST=127.0.0.1
      - PORT=7434
      - DD_DISABLED=true
      - DB_PATH=/app/.omg/data
      - APP_ENV=localwatcher
    ports:
      - "7434:7434"
    healthcheck:
      test: curl watcher:7434
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  watcher_informational:
    image: omisego/watcher_informational:latest
    command: "full_local"
    environment:
      - ETHEREUM_RPC_URL=https://rinkeby.infura.io/v3/${INFURA_API_KEY}
      - ETHEREUM_WS_RPC_URL=wss://rinkeby.infura.io/ws/v3/${INFURA_API_KEY}
      - CHILD_CHAIN_URL=https://childchain-pre-lumphini.omg.network/
      - ETHEREUM_NETWORK=RINKEBY
      - RINKEBY_TXHASH_CONTRACT=0xefc216dcfb01223253172514355fbe65e60acc043f214a9cdfad1e6f5cb566b4
      - RINKEBY_AUTHORITY_ADDRESS=0x3272b97b7f1b74b338cb0fdda167cf76bc4da3b6
      - RINKEBY_CONTRACT_ADDRESS_PLASMA_FRAMEWORK=0x24e0b6b701c941824b3eedc041f50be6e15bfdeb
      - RINKEBY_CONTRACT_ADDRESS_ETH_VAULT=0x9631a230eaf33b51012fca494e4030d852bb9386
      - RINKEBY_CONTRACT_ADDRESS_ERC20_VAULT=0x88d38a42946c62d32f159880fe2735c0149cca3f
      - RINKEBY_CONTRACT_ADDRESS_PAYMENT_EXIT_GAME=0x51db5309cc89165b5306417b63368acce690355b
      - DATABASE_URL=postgresql://omisego_dev:omisego_dev@postgres:5432/omisego_dev
      - NODE_HOST=127.0.0.1
      - PORT=7534
      - DD_DISABLED=true
      - DB_PATH=/app/.omg/data
      - APP_ENV=localwatcher_informational
    restart: always
    ports:
      - "7534:7534"
    healthcheck:
      test: curl watcher_informational:7534
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      plasma-contracts:
        condition: service_healthy
      childchain:
        condition: service_healthy
      postgres:
        condition: service_healthy

