components:
  schemas:
    deposit_finality_margin:
      type: integer
    contract_semver:
      type: string
    exit_processor_sla_seconds:
      type: integer
    network:
      type: string
      